site_name: AGL Application Framework Binder
theme: readthedocs
docs_dir: docs
pages:
- 'Document revisions' : '0-Doc-Revisions.md'
- '1. Prequisites': '1_Prerequisites.md'
- '2. AGL Application Framework Installation': '2_AGL_Application_Framework.md'
- '3. AGL XDS Installation.md': '3_AGL_XDS.md'
- '4. CanDevStudio Installation': '4_Candevstudio.md'
